#This is my attempt at creating an automated solution for building local web
#servers using docker. To create a new site, you just need to change the service
#name, container name, port number, and folder name. This is usually done using
#version numbers (website1, website2, website3) for simplicity and organization.
#What is nice is that this can be done pretty much indefinitely up to hundreds of sites.
#In the near future i'd like to find a way to automate that process as well, but
#until now this is much quicker than the alternatives. 
version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
    - '8080:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs
    - ./website/images:/usr/local/apache2/htdocs/images

  apache2:
    image: httpd:latest
    container_name: pcservicesite
    ports:
    - '8081:80'
    volumes:
    - ./website2:/usr/local/apache2/htdocs
    - ./website2/images:/usr/local/apache2/htdocs/images

  apache3:
    image: httpd:latest
    container_name: csstesting
    ports:
    - '8082:80'
    volumes:
    - ./website3:/usr/local/apache2/htdocs
    - ./website3/images:/usr/local/apache2/htdocs/images

  apache4:
    image: httpd:latest
    container_name: csslayout
    ports:
    - '8083:80'
    volumes:
    - ./website4:/usr/local/apache2/htdocs
    - ./website4/images:/usr/local/apache2/htdocs/images
